export const McaTwoColumns = [
    "ID",
    "Application No.",
    "Register Number",
    "Name",
    "Student Contact No.",
    "Date of Birth",
    "Date of Joining (from 12/07/2024)",
    "Gender (Male/ Female)",
    "Blood Group",
    "Nationality",
    "Religion",
    "Community",
    "Caste",
    "Boarding Status\n (Hostel / Day Scholar)",
    "Father Name",
    "Father Number",
    "Mother Name",
    "Mother Number",
    "Guardian Name",
    "Relationship",
    "Parent's Phone No.",
    "Door No. & Street",
    "Town/ Village",
    "Post",
    "Taluk",
    "District",
    "State",
    "Pincode",
    "Country",
    "Email Id (College)",
    "Email Id (Personal)",
    "SSLC - Marks (%)",
    "HSC - Marks (%)",
    "UG-BCA/ B.Sc. (CS/IT)",
    "Passed Out Year",
    "UG - Marks (%)",
    "Alumni (SRM Student-UG)",
    "College Name",
    "University/ Autonomous(Uni.)/ Govt. College",
    "College Place",
    "College State",
    "Extra Curricular Activities (Participate/ Member)",
    "Licence Number",
    "Passport Number",
    "Aadhaar Number"
]